{
 "title": "QuakeWatch Application Metrics",
 "tags": [
  "quakewatch",
  "flask"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_total{job=\"earthquake-app-quackwatch-helm\"}[5m])"
    }
   ]
  },
  {
   "title": "Response Time (p95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket{job=\"earthquake-app-quackwatch-helm\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=\"earthquake-app-quackwatch-helm\",status=~\"4..|5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{job=\"earthquake-app-quackwatch-helm\"})"
    }
   ]
  }
 ]
}