# Default values for QuakeWatch application
replicaCount: 3

image:
  repository: blaqr/earthquake
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 32000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 2

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

# ConfigMap settings
config:
  appEnv: production
  appVersion: "1.0.3"

# Secret settings (API keys)
secrets:
  apiKey: ""  # Set via --set secrets.apiKey=<value> or override in values file (plain text, will be base64 encoded)

# Persistent Volume Claim for shared logs
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# CronJob settings
cronJob:
  enabled: true
  schedule: "* * * * *"  # Every minute
  ttlSecondsAfterFinished: 300

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}